-- Plataforma MundoChile
-- Migration: Disponibilidad de intérpretes v1
-- Alcance:
--   1) Crear disponibilidad por fecha específica, sin recurrencia.
--   2) Relacionar cada registro con interpretes.id.
--   3) Aplicar RLS según la matriz definitiva.
-- NO aplicar directamente en Supabase hasta completar la revisión/prueba.

begin;

create table if not exists public.disponibilidad_interpretes (
  id bigint generated by default as identity primary key,
  interprete_id bigint not null,
  fecha date not null,
  hora_desde time,
  hora_hasta time,
  disponible boolean not null default true,
  modalidad text not null default 'Ambas',
  observaciones text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint disponibilidad_interpretes_interprete_fkey
    foreign key (interprete_id)
    references public.interpretes(id)
    on delete cascade,

  constraint disponibilidad_interpretes_modalidad_check
    check (modalidad in ('Presencial','Remoto','Ambas')),

  constraint disponibilidad_interpretes_horario_check
    check (
      (hora_desde is null and hora_hasta is null)
      or (hora_desde is not null and hora_hasta is not null and hora_hasta > hora_desde)
    )
);

create index if not exists idx_disponibilidad_interpretes_interprete_fecha
  on public.disponibilidad_interpretes (interprete_id, fecha);

create index if not exists idx_disponibilidad_interpretes_fecha
  on public.disponibilidad_interpretes (fecha);

-- Mantiene updated_at sincronizado en cada modificación.
-- Se crea un trigger local para no depender de los triggers históricos del esquema.
create or replace function public.update_disponibilidad_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $
begin
  new.updated_at = now();
  return new;
end;
$;

revoke all on function public.update_disponibilidad_updated_at() from public;

 drop trigger if exists trg_disponibilidad_updated_at
  on public.disponibilidad_interpretes;

create trigger trg_disponibilidad_updated_at
before update on public.disponibilidad_interpretes
for each row
execute function public.update_disponibilidad_updated_at();

alter table public.disponibilidad_interpretes enable row level security;

-- Elimina cualquier política previa de esta tabla si la migración se reaplica.
drop policy if exists disponibilidad_admin_all
  on public.disponibilidad_interpretes;
drop policy if exists disponibilidad_editor_all
  on public.disponibilidad_interpretes;
drop policy if exists disponibilidad_interprete_select
  on public.disponibilidad_interpretes;
drop policy if exists disponibilidad_interprete_insert
  on public.disponibilidad_interpretes;
drop policy if exists disponibilidad_interprete_update
  on public.disponibilidad_interpretes;
drop policy if exists disponibilidad_interprete_delete
  on public.disponibilidad_interpretes;

-- Admin: gestión total.
create policy disponibilidad_admin_all
on public.disponibilidad_interpretes
for all to authenticated
using (public.get_user_rol() = 'admin')
with check (public.get_user_rol() = 'admin');

-- Editor: gestión total de disponibilidades operativas.
create policy disponibilidad_editor_all
on public.disponibilidad_interpretes
for all to authenticated
using (public.get_user_rol() = 'editor')
with check (public.get_user_rol() = 'editor');

-- Intérprete: puede consultar únicamente su propia disponibilidad.
create policy disponibilidad_interprete_select
on public.disponibilidad_interpretes
for select to authenticated
using (
  public.get_user_rol() = 'interprete'
  and interprete_id = public.get_interprete_id()
);

-- Intérprete: puede crear disponibilidad únicamente para sí mismo.
create policy disponibilidad_interprete_insert
on public.disponibilidad_interpretes
for insert to authenticated
with check (
  public.get_user_rol() = 'interprete'
  and interprete_id = public.get_interprete_id()
);

-- Intérprete: puede modificar únicamente sus propios registros.
create policy disponibilidad_interprete_update
on public.disponibilidad_interpretes
for update to authenticated
using (
  public.get_user_rol() = 'interprete'
  and interprete_id = public.get_interprete_id()
)
with check (
  public.get_user_rol() = 'interprete'
  and interprete_id = public.get_interprete_id()
);

-- Intérprete: puede eliminar únicamente sus propios registros.
create policy disponibilidad_interprete_delete
on public.disponibilidad_interpretes
for delete to authenticated
using (
  public.get_user_rol() = 'interprete'
  and interprete_id = public.get_interprete_id()
);

-- Viewer: sin acceso a la tabla de disponibilidad.
-- La matriz aprobada define Viewer como sin acceso a disponibilidad.

commit;

-- ============================================================
-- FIN — Disponibilidad de intérpretes v1
-- ============================================================
